# Generated by Django 3.0.7 on 2020-11-20 13:43

import CVApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0002_auto_20201120_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='certificates',
            field=models.FileField(blank=True, default='no-img.jpg', upload_to=CVApp.models.get_upload_path),
        ),
    ]
