# Generated by Django 3.0.7 on 2020-12-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0003_auto_20201120_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('From', models.EmailField(default='', max_length=10)),
                ('Subject', models.CharField(default='', max_length=100)),
                ('Message', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
