# Generated by Django 3.0.7 on 2020-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0004_auto_20201204_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='From',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
