# Generated by Django 2.1.1 on 2020-12-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0005_auto_20201204_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='Github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(default=''),
        ),
    ]
