# Generated by Django 2.1.1 on 2020-12-05 19:40

import CVApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0006_auto_20201206_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_you',
            field=models.FileField(blank=True, default='video.mp4', upload_to=CVApp.models.get_upload_path),
        ),
    ]
