# Generated by Django 2.1.1 on 2020-12-05 19:43

import CVApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVApp', '0007_auto_20201206_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about_you',
            field=models.FileField(blank=True, upload_to=CVApp.models.get_upload_path),
        ),
    ]
